### ISSUE TITLE
can't render with kick

### ISSUE THREAD

**Issue by ryethehomie** [mruegenberg/mrAiHouOceanShader#2]
hey Marcel,

awesome work on the htoa ocean shader. Arnold is my daily driver, so i cant stress enough how happy i am seeing this product.

So far everything's been fine rendering within Houdini, however I can't seem to get it render with kick. It appeared to be missing dependencies / libraries from HDK.

```
WARNING |  unable to load dynamic library /Volumes/dev/arnold/plugins/ai_ocean_samplelayers.so: libHoudiniUI.so: cannot open shared object file: No such file or directory
ERROR   |  [ass] line 131: node "ai_ocean_samplelayers" is not installed
```

**Comment by mruegenberg** [comment]
Hello,
very glad it's appreciated :)
Could you try adding `-l [path-to-dsolib]` to your kick call?
[path-to-dsolib] would be something like `/opt/hfs18.5.563/dsolib`.

Also, there should be an equivalent program called `hick`, which is a Houdini variant of `kick`. Could you try that one as well?

**Comment by kikou** [comment]
Hi,

`hick` is not designed as replacement for `kick`, it's used internally to run Arnold renders as a separate process.

You need to add the Houdini DSO path to the `LD_LIBRARY_PATH` environment variable before you run `kick` for the shader to pick up the Houdini libraries.

**Comment by ryethehomie** [comment]
> Hi,
> 
> `hick` is not designed as replacement for `kick`, it's used internally to run Arnold renders as a separate process.
> 
> You need to add the Houdini DSO path to the `LD_LIBRARY_PATH` environment variable before you run `kick` for the shader to pick up the Houdini libraries.

this works! Thanks

**Comment by mruegenberg** [comment]
Brilliant, thanks for the help @kikou
